pmd0: &pmd0
  command: |
    start
    set verbose 1
  result: Change verbose level from \d{1,} to 1

pmd1: &pmd1
  command: |
    flow create 0 ingress pattern eth / ipv4 / udp / end actions jump group 1 / end
    flow create 0 ingress group 1 pattern eth / end actions mark id 0xaaa / rss / end
  result: (Flow rule \#\d created.*){2}


phase0: &phase0
  name: configuration
  tg: |
    udp_packet = Ether(src='11:22:33:44:55:66', dst='aa:bb:cc:dd:ee:aa')/IP(src='1.1.1.1', dst='2.2.2.2')
    udp_packet /= UDP(sport=1234, dport=5678)/Raw('== TEST ==')
  pmd: [ *pmd0, *pmd1 ]

phase1: &phase1
  name: send and check
  tg: |
    sendp(udp_packet, iface=pf0)
  result:
    pmd: FDIR matched ID=0xaaa

#### 

prog: 'dpdk-testpmd -a pf0 -- -i'

flow:
  -
    phases: [ *phase0 ]
    repeat: 1
  -
    phases: [ *phase1 ]
    repeat: 3

setup:
  hca: any #
  fw: any
  hws: True
  pf: [nic, fdb]
  vf: [2, 2]
  sf: [0, 0]
